[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size=14
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0 # For line spacing (default: 0)

# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#f1f1f1"
background = "#000000"
