[font]
normal = { family = "Courier", style = "Regular" }
size=14

# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#000000"
background = "#e0e0e0"
