[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size=12
# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#ffffff"
background = "#000000"
